# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\brehm\\OneDrive\\Python\\EZPZ Family\\EZPZ Plotting'],
             # pathex=[r'C:\Users\jakem\OneDrive\Python\EZPZ Family\EZPZ Plotting'],
             binaries=[],
             datas=[('settings.py', '.'),
                    ('controls.py', '.'),
                    ('basic.py', '.'),
                    ('peakvalley.py', '.'),
                    ('assets\\browse.png', 'assets'),
                    ('assets\\checking.png', 'assets'),
                    ('assets\\clear.png', 'assets'),
                    ('assets\\controls.png', 'assets'),
                    ('assets\\copy.png', 'assets'),
                    ('assets\\icon.ico', 'assets'),
                    ('assets\\logo.png', 'assets'),
                    ('assets\\minus.png', 'assets'),
                    ('assets\\paste.png', 'assets'),
                    ('assets\\plot.png', 'assets'),
                    ('assets\\plotting.png', 'assets'),
                    ('assets\\plus.png', 'assets'),
                    ('assets\\reading.png', 'assets'),
                    ('assets\\tactair.bmp', 'assets'),
                    ('assets\\yf.bmp', 'assets')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='EZPZ Plotting',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False , icon='assets\\icon.ico')
